import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {Search,Layers3,RotateCcw,Focus,Eye,ChevronRight,ArrowUpRight,Download,Info,X,SlidersHorizontal,Moon,Sun} from './icons';
import Scene from './Scene';
import NeuralAtlas from './NeuralAtlas';
import {ReferenceNotes,UpdatedSources} from './references';
import {DEFAULT_LAYERS,SYSTEMS,matchesPart,partOpacity,sourceLink,type Atlas,type LayerState,type SceneState,type SystemId} from './atlas';

export default function App(){
  const [theme,setTheme]=useState<'light'|'dark'>(()=>{
    try{const saved=localStorage.getItem('worm-atlas-theme');if(saved==='light'||saved==='dark')return saved;}catch{/* Storage may be unavailable in private contexts. */}
    return 'light';
  });
  useEffect(()=>{document.documentElement.style.colorScheme=theme;try{localStorage.setItem('worm-atlas-theme',theme);}catch{/* The toggle still works without storage. */}},[theme]);
  const [pan,setPan]=useState(false);
  const [atlas,setAtlas]=useState<Atlas|null>(null),[error,setError]=useState(''),[ready,setReady]=useState(false);
  const [layers,setLayers]=useState<LayerState>({...DEFAULT_LAYERS}),[selected,setSelected]=useState<string|null>(null),[isolate,setIsolate]=useState(false);
  const [query,setQuery]=useState(''),[focus,setFocus]=useState(0),[reset,setReset]=useState(0);
  const [view,setView]=useState<SceneState['view']>('oblique'),[separation,setSeparation]=useState(0),[compare,setCompare]=useState<string[]>([]),[comparing,setComparing]=useState(false),[mode,setMode]=useState<'body'|'neural'>('body'),[cut,setCut]=useState(0);
  const [about,setAbout]=useState(false),[sidebar,setSidebar]=useState(()=>window.innerWidth>760),[searchOpen,setSearchOpen]=useState(false),[advanced,setAdvanced]=useState(false);
  const search=useRef<HTMLInputElement>(null),dialog=useRef<HTMLDialogElement>(null);
  const onReady=useCallback(()=>setReady(true),[]),onError=useCallback((message:string)=>setError(message),[]);
  useEffect(()=>{const c=new AbortController();fetch('./atlas/manifest.json',{signal:c.signal}).then(r=>{if(!r.ok)throw new Error('The anatomy manifest could not be loaded.');return r.json();}).then(setAtlas).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return ()=>c.abort();},[]);
  useEffect(()=>{if(about)dialog.current?.showModal();else dialog.current?.close();},[about]);
  useEffect(()=>{if(searchOpen)search.current?.focus();},[searchOpen]);
  useEffect(()=>{const key=(e:KeyboardEvent)=>{const target=e.target as HTMLElement;if(e.key==='Escape'){setSearchOpen(false);setIsolate(false);setSelected(null);}if(target.matches('input,textarea,select'))return;if(e.key==='/'){e.preventDefault();setSearchOpen(true);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
  const part=atlas?.parts.find(p=>p.id===selected);
  const results=useMemo(()=>atlas?.parts.filter(p=>matchesPart(p,query)).sort((a,b)=>a.name.localeCompare(b.name,undefined,{numeric:true}))??[],[atlas,query]);
  const visible=atlas?.parts.filter(p=>isolate?p.id===selected:comparing?compare.includes(p.id):partOpacity(p,layers)>0).length??0;
  const choose=useCallback((id:string)=>{setSelected(id);setSearchOpen(false);const p=atlas?.parts.find(p=>p.id===id);if(p)setLayers(previous=>({...previous,[p.systems[0]]:Math.max(previous[p.systems[0]],.75)}));},[atlas]);
  const preset=(id:SystemId|'all'|'organs')=>{setIsolate(false);setComparing(false);setLayers(id==='all'?{...DEFAULT_LAYERS}:Object.fromEntries(SYSTEMS.map(s=>[s.id,id==='organs'?(['reproductive','digestive','excretory'].includes(s.id)?1:0):s.id===id?1:0])) as LayerState);};
  const resetView=()=>{setView('oblique');setSeparation(0);setCut(0);setIsolate(false);setComparing(false);setReset(n=>n+1);};
  const state:SceneState={pan,layers,selected,isolate,focus,reset,view,layout:comparing?'selection':'structures',separation,compare,cut};
  const closePart=()=>{setSelected(null);if(isolate){setIsolate(false);setReset(n=>n+1);}};
  return <div data-theme={theme} className={`app ${mode==='neural'?'neural-mode':''} ${part?'has-selection':''} ${sidebar?'':'controls-hidden'}`}>
    <header className="identity"><p className="eyebrow"><span/> VIRTUAL WORM / EXPLORER</p><h1><i>C. elegans</i> Atlas <span className="badge">3D</span></h1><p className="model-credit">{mode==='body'?<>{atlas?.summary.objects??'…'} modeled objects <span>·</span> Virtual Worm · 2012</>:<>Regional source meshes <span>·</span> Witvliet 2021 · NeuroSC 2025</>}</p><nav className="dataset-nav" aria-label="Atlas dataset"><button aria-pressed={mode==='body'} onClick={()=>{if(mode!=='body'){setReady(false);setError('');}setMode('body');}}>Whole body</button><button aria-pressed={mode==='neural'} onClick={()=>setMode('neural')}>Neural EM <span>2021 / 2025</span></button></nav></header>
    <div className="top-actions">{mode==='body'&&<button className="search-trigger" aria-label="Find a structure" onClick={()=>setSearchOpen(s=>!s)} aria-expanded={searchOpen}><Search size={18}/><span>Find a structure</span><kbd>/</kbd></button>}<button className="icon-button theme-toggle" aria-label={theme==='dark'?'Switch to light theme':'Switch to dark theme'} title={theme==='dark'?'Switch to light theme':'Switch to dark theme'} onClick={()=>setTheme(t=>t==='dark'?'light':'dark')}>{theme==='dark'?<Sun size={18}/>:<Moon size={18}/>}</button><button className="icon-button" aria-label="About the model" onClick={()=>setAbout(true)}><Info size={19}/></button></div>
    {mode==='neural'?<NeuralAtlas/>:<main className="studio" aria-label="Whole-body anatomy">
      <section className="viewer" aria-label="Anatomy viewer">
        {atlas&&<Scene atlas={atlas} state={state} onSelect={choose} onReady={onReady} onError={onError}/>}
        {!ready&&!error&&<div className="loading"><div className="loading-ring"/><strong>Loading source anatomy</strong><p>{atlas?`${(atlas.summary.gzipBytes/1e6).toFixed(1)} MB · original exported geometry`:'Reading the model inventory…'}</p></div>}
        {error&&<div className="loading error" role="alert"><Info size={24}/><strong>3D view unavailable</strong><p>{error}</p><button onClick={()=>window.location.reload()}>Reload atlas</button></div>}
      </section>
      <button className="systems-trigger icon-button" aria-label={sidebar?'Hide systems panel':'Show systems panel'} aria-expanded={sidebar} onClick={()=>setSidebar(s=>!s)}><Layers3 size={19}/></button>
      {sidebar&&<aside className="systems-panel panel" aria-label="Anatomy controls"><div className="panel-heading"><h2>Systems</h2><span className="count-badge">{SYSTEMS.length}</span></div><div className="presets"><button onClick={()=>preset('all')}>All</button><button onClick={()=>preset('nervous')}>Neural</button><button onClick={()=>preset('organs')}>Organs</button></div><div className="system-list">{SYSTEMS.map(system=><div className={`system ${layers[system.id]===0?'muted':''}`} key={system.id}><div className="system-row"><span className="color-dot" style={{background:system.color}}/><button className="system-name" onClick={()=>preset(system.id)} title={`Show only ${system.name}`}>{system.name}</button><span className="system-count" title="Source object count; shared memberships overlap">{atlas?.parts.filter(p=>p.systems.includes(system.id)).length??'–'}</span><button className="switch" role="switch" aria-checked={layers[system.id]>0} aria-label={`${system.name} visibility`} onClick={()=>{setIsolate(false);setComparing(false);setLayers(l=>({...l,[system.id]:l[system.id]>0?0:DEFAULT_LAYERS[system.id]}));}}/></div>{advanced&&<div className="opacity-row"><input type="range" aria-label={`${system.name} opacity`} min="0" max="100" value={Math.round(layers[system.id]*100)} onChange={e=>{setIsolate(false);setLayers(l=>({...l,[system.id]:Number(e.target.value)/100}));}}/><span>{Math.round(layers[system.id]*100)}%</span></div>}</div>)}</div><div className="panel-footer"><span>{visible} {visible===1?'object':'objects'} visible</span><button onClick={()=>{setIsolate(false);setComparing(false);setLayers(Object.fromEntries(SYSTEMS.map(s=>[s.id,visible?0:DEFAULT_LAYERS[s.id]])) as LayerState);}}>{visible?'Hide all':'Show all'}</button></div><button className="display-settings" aria-expanded={advanced} onClick={()=>setAdvanced(v=>!v)}><SlidersHorizontal size={13}/> Display settings</button>{advanced&&<div className="advanced-settings"><label>Cutaway <output>{cut}%</output><input type="range" aria-label="Cutaway depth" min="0" max="100" value={cut} disabled={separation>0} onChange={e=>setCut(Number(e.target.value))}/></label><small>Counts refer to source objects; shared memberships overlap. Cutaway clips the display.</small></div>}</aside>}
      {searchOpen&&<section className="search-panel panel" aria-label="Find a structure"><div className="search-box"><Search size={18}/><input ref={search} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, cell or system…" aria-label="Search structures"/><button aria-label="Close search" onClick={()=>setSearchOpen(false)}><X size={17}/></button></div><div className="search-summary">{results.length} source {results.length===1?'object':'objects'}</div><div className="results" aria-label="Structure results">{results.map(p=><button className="result" key={p.id} onClick={()=>choose(p.id)}><span className="color-dot" style={{background:SYSTEMS.find(s=>s.id===p.systems[0])!.color}}/><span>{p.name}<small>{p.group}</small></span><ChevronRight size={14}/></button>)}{!results.length&&<p className="empty">No matching objects. Try AVAL or a tissue name.</p>}</div></section>}
      <div className="camera-tools panel" aria-label="Camera controls"><button title="Drag to move the view without rotating" aria-label="Pan view" aria-pressed={pan||separation>80} disabled={separation>80} onClick={()=>setPan(p=>!p)}>Pan</button><hr/><button title="Oblique view" aria-label="Oblique view" aria-pressed={view==='oblique'&&separation<=80} disabled={separation>80} onClick={()=>setView('oblique')}>Oblique</button><button title="Side view" aria-label="Side view" aria-pressed={view==='side'||separation>80} onClick={()=>setView('side')}>Side</button><button title="Reverse view" aria-label="Reverse view" aria-pressed={view==='opposite'&&separation<=80} disabled={separation>80} onClick={()=>setView('opposite')}>Reverse</button><hr/><button title="Fit anatomy" aria-label="Fit anatomy" onClick={()=>setReset(n=>n+1)}><Focus size={18}/></button><button title="Reset view" aria-label="Reset view" onClick={resetView}><RotateCcw size={18}/></button></div>
      {part&&atlas&&<aside className="detail-sheet panel" aria-label="Structure inspector"><button className="sheet-close" aria-label="Close structure details" onClick={closePart}><X size={18}/></button><p className="eyebrow">SELECTED SOURCE OBJECT</p><h2>{part.name}</h2><p className="part-group">{part.group}</p><div className="inspect-actions"><button onClick={()=>{setCut(0);setFocus(n=>n+1);}} disabled={!ready}><Focus size={15}/> Focus</button><button aria-pressed={isolate} onClick={()=>{setIsolate(!isolate);setCut(0);setReset(n=>n+1);}} disabled={!ready}><Eye size={15}/>{isolate?'Show context':'Isolate'}</button></div><button className="compare-button" aria-pressed={compare.includes(part.id)} onClick={()=>setCompare(ids=>ids.includes(part.id)?ids.filter(id=>id!==part.id):[...ids,part.id])}>{compare.includes(part.id)?'Remove from comparison':'+ Add to comparison'}</button>{compare.length>0&&<div className="comparison-tray"><div className="panel-heading"><h3>Comparison · {compare.length}</h3><button onClick={()=>{setCompare([]);setComparing(false);}}>Clear</button></div>{compare.map(id=><button key={id} aria-label={`Remove ${atlas.parts.find(p=>p.id===id)?.name} from comparison`} onClick={()=>setCompare(ids=>ids.filter(x=>x!==id))}>{atlas.parts.find(p=>p.id===id)?.name}<X size={12}/></button>)}<button className="align-button" disabled={compare.length<2} onClick={()=>{setComparing(true);setSeparation(100);setCut(0);setIsolate(false);}}>Align comparison</button>{comparing&&<button onClick={()=>setComparing(false)}>Show all visible structures</button>}</div>}<ReferenceNotes part={part}/><details><summary>Object details & sources</summary><dl className="metadata"><dt>Source name</dt><dd>{part.sourceName}</dd><dt>Reference</dt><dd>Adult hermaphrodite</dd><dt>Exported pieces</dt><dd>{part.segments.length}</dd></dl><p className="dataset-description">This object retains its exported shape. Reset restores source positions; its identity has not been independently confirmed from microscopy.</p><a className="reference-link" href={sourceLink(atlas,part)} target="_blank" rel="noreferrer">Source metadata <ArrowUpRight size={14}/></a><a className="reference-link" href={SYSTEMS.find(s=>s.id===part.systems[0])!.url} target="_blank" rel="noreferrer">WormAtlas context <ArrowUpRight size={14}/></a></details></aside>}
      <div className="explode-area"><p className="specimen-label">{comparing?'SELECTED STRUCTURES':separation>95?'SOURCE OBJECT INVENTORY':'ADULT HERMAPHRODITE'}<span/></p><div className="explode-panel panel"><div className="explode-slider"><label htmlFor="explode">Separate anatomy <output htmlFor="explode">{separation}<span> %</span></output></label><input id="explode" type="range" min="0" max="100" value={separation} aria-label="Explode anatomy" style={{'--progress':`${separation}%`} as React.CSSProperties} onChange={e=>{setSeparation(Number(e.target.value));setIsolate(false);setCut(0);}}/><div className="slider-labels"><span>Assembled</span><span>Every piece</span></div></div><button className="explode-reset" onClick={resetView}><RotateCcw size={18}/><span>Reset</span></button></div><p className="arrangement-caption">{separation>0?'Display separation only · Shapes and relative sizes preserved':cut>0?'Display clipping only · Open surfaces are not anatomical boundaries':' '}</p></div>
    </main>}
    <footer className="footer"><span>{pan||separation>80?'Drag to pan':'Drag to rotate · Shift-drag to pan'} <b>·</b> Pinch to zoom <b>·</b> Tap to inspect</span><button onClick={()=>setAbout(true)}>Source & credits <ArrowUpRight size={15}/></button></footer>
    <dialog ref={dialog} onCancel={()=>setAbout(false)} onClick={e=>{if(e.target===e.currentTarget)setAbout(false);}}><button className="dialog-close" aria-label="Close model information" onClick={()=>setAbout(false)}><X size={20}/></button><h2>About this atlas</h2><Evidence atlas={atlas}/><a className="reference-link" href="./atlas/inventory.tsv" download><Download size={14}/> Download source inventory</a></dialog>
  </div>;
}

function Evidence({atlas}:{atlas:Atlas|null}){
  return <div className="evidence"><h2>Traceable anatomy.</h2><p>Adult hermaphrodite reconstruction from <a href="https://caltech.wormbase.org/virtualworm/" target="_blank" rel="noreferrer">Virtual Worm</a>, using the February 2012 geometry distributed by OpenWorm.</p>
    <div className="evidence-stat"><strong>{atlas?.summary.objects??'–'}</strong><span>named source objects<br/>Not a count of individual cells</span></div>
    <UpdatedSources/>
    <h3>What is verified</h3><p>Every exported triangle, referenced vertex position and normal is retained. Split pieces with identical source names are joined. The conversion is compared against the original decoder.</p><a className="reference-link" href="./atlas/validation.json" target="_blank" rel="noreferrer">Conversion validation record <ArrowUpRight size={14}/></a>
    <h3>Known coverage gap</h3><p>The export contains {atlas?.summary.neuronNamedObjects??'301'} neuron-named objects. AIZR is listed by WormAtlas but has no named geometry in this export. No substitute geometry has been invented.</p><a className="reference-link" href="https://www.wormatlas.org/neurons/Individual%20Neurons/neuronsmainframe.htm" target="_blank" rel="noreferrer">WormAtlas neuron list <ArrowUpRight size={14}/></a>
    <h3>Limits of the model</h3><ul><li>Historical reconstruction; not a direct 3D scan of one animal.</li><li>No guarantee of complete anatomy or independently verified cell identity.</li><li>The upstream browser geometry is already quantized. No further simplification is applied here.</li><li>This whole-body view contains no male, larval, gene-expression or synaptic connectivity data. The separate Neural EM view includes L1 and adult regional meshes from the 2021 study.</li><li>Colors and transparency are display settings. No physical scale or quantitative tissue measurements are asserted.</li></ul>
    <p>Legacy neuron categories are source metadata only. Some source objects represent tissues or fused structures rather than single cells.</p>
    <a className="reference-link" href="./atlas/accuracy-notes.md" target="_blank" rel="noreferrer">Full accuracy and provenance notes <ArrowUpRight size={14}/></a>
    <a className="reference-link" href="./atlas/source-files.json" target="_blank" rel="noreferrer">Source files and checksums <ArrowUpRight size={14}/></a>
    <p className="credit">Virtual Worm: Chris Grove, WormBase, Caltech. OpenWorm export: MIT license. Interface inspired by <a href="https://github.com/ashemag/human-atlas" target="_blank" rel="noreferrer">Human Atlas</a>.</p>
  </div>;
}
