import {useEffect,useState} from 'react';
import NeuralScene from './NeuralScene';
import {UpdatedSources} from './references';

export interface NeuralObject {uid:string;filename:string;local:string;url:string;sha256:string;bytes:number;color:number[]}
export interface NeuralDataset {id:string;label:string;stage:string;timepoint:number;sourceYear:number;platformYear:number;scope:string;objects:NeuralObject[]}
interface Catalog {retrieved:string;datasets:NeuralDataset[]}
export default function NeuralAtlas(){
  const [pan,setPan]=useState(false);
  const [catalog,setCatalog]=useState<Catalog|null>(null),[error,setError]=useState('');
  const [datasetId,setDatasetId]=useState('neurosc-45'),[query,setQuery]=useState('');
  const [ids,setIds]=useState<string[]>(['AVAL','AVAR']),[aligned,setAligned]=useState(false),[reset,setReset]=useState(0);
  const dataset=catalog?.datasets.find(d=>d.id===datasetId);
  useEffect(()=>{const a=new AbortController();fetch('./neurosc/catalog.json',{signal:a.signal}).then(r=>{if(!r.ok)throw Error('Neural dataset catalog could not be loaded.');return r.json();}).then(setCatalog).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>a.abort();},[]);
  const objects=dataset?.objects.filter(o=>o.uid.toLowerCase().includes(query.trim().toLowerCase()))??[];
  const changeDataset=(id:string)=>{const d=catalog!.datasets.find(d=>d.id===id)!;setDatasetId(id);setIds(current=>current.filter(uid=>d.objects.some(o=>o.uid===uid)));setReset(n=>n+1);};
  return <main className="workspace neural-workspace">
    <aside className="sidebar neural-controls"><h2>Explore neural EM</h2><label className="field-label">Source dataset<select aria-label="Neural dataset" value={datasetId} onChange={e=>changeDataset(e.target.value)}>{catalog?.datasets.map(d=><option key={d.id} value={d.id}>{d.label}</option>)}</select></label><p className="dataset-description">Study: Witvliet et al., 2021.<br/>Meshes distributed through NeuroSC (2025).</p><label className="field-label">Find a source object<input type="search" aria-label="Search neural objects" placeholder="e.g. AVAL or AIZR" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="section-title"><h3>{objects.length} catalog objects</h3><button onClick={()=>setIds([])}>Clear view</button></div><p className="dataset-description">Select up to 12 objects for detailed comparison. Every archived object is searchable.</p><div className="results neural-results">{objects.map(o=><label key={o.uid} className="neural-result"><input type="checkbox" aria-label={`Show ${o.uid}`} checked={ids.includes(o.uid)} disabled={ids.length>=12&&!ids.includes(o.uid)} onChange={()=>setIds(old=>old.includes(o.uid)?old.filter(x=>x!==o.uid):[...old,o.uid])}/><span className="color-dot" style={{background:`rgb(${o.color.slice(0,3).map(c=>Math.round(c*255)).join(',')})`}}/>{o.uid}<a href={o.local} download aria-label={`Download ${o.uid} source mesh`}>↓</a></label>)}{!objects.length&&<p className="empty">No matching objects in this dataset.</p>}</div></aside>
    <section className="viewer neural-viewer" aria-label="Neural EM viewer"><div className="viewer-top"><div><h1>Inside the nerve ring.</h1><p>{dataset?.label} · Source study 2021 · NeuroSC 2025</p></div></div>{dataset&&<NeuralScene dataset={dataset} ids={ids} aligned={aligned} reset={reset} pan={pan}/>}<div className="view-controls"><button title="Drag to move the view without rotating" aria-label="Pan view" aria-pressed={pan||aligned} disabled={aligned} className={pan||aligned?'active':''} onClick={()=>setPan(p=>!p)}>Pan</button><button aria-pressed={!aligned} className={!aligned?'active':''} onClick={()=>setAligned(false)}>Source arrangement</button><button aria-pressed={aligned} className={aligned?'active':''} onClick={()=>setAligned(true)}>Align objects</button><button onClick={()=>setReset(n=>n+1)}>Fit view</button></div>{error&&<div className="loading error" role="alert">{error}</div>}<div className="viewer-bottom"><p className="spatial-note">{aligned?'Display alignment: positions displaced; relative sizes preserved.':'Coordinates retained within this dataset; no registration to the whole-body model.'}</p><div className="viewer-hint"><span>{pan||aligned?'Drag to pan':'Drag to rotate · Shift-drag to pan'} · Scroll to zoom</span><span>{ids.length} selected / {dataset?.objects.length??0} archived</span></div></div></section>
    <details className="inspector neural-inspector"><summary>EM source & coverage</summary><p className="dataset-description">Regional segmented meshes, not complete neuron shapes or a whole-body scan. Dataset labels and colors come from NeuroSC.</p><dl className="metadata"><dt>Source study</dt><dd>2021</dd><dt>Platform paper</dt><dd>2025</dd><dt>Downloaded</dt><dd>{catalog?.retrieved}</dd><dt>Coverage</dt><dd>Nerve-ring region</dd></dl><p className="dataset-description">Different timepoints represent different animals. Switching datasets does not track the same individual. No cross-stage registration or tissue-volume measurement is asserted.</p><div className="context-note"><h3>Displayed source files</h3>{ids.map(id=>{const o=dataset?.objects.find(o=>o.uid===id);return o?<a key={id} className="reference-link" href={o.url} target="_blank" rel="noreferrer">{id} · original glTF ↗</a>:null;})}</div><UpdatedSources/></details>
  </main>;
}
