import type {Part} from './atlas';

export const references=[
  {id:'ava',title:'AVA interneurons',url:'https://www.wormatlas.org/neurons/Individual%20Neurons/AVAmainframe.htm',revision:'19 July 2024',text:'WormAtlas identifies AVAL and AVAR as interneurons with cell bodies in the lateral ganglia of the head.',quote:'Location: Lateral ganglia of head',matches:(p:Part)=>/^ava[lr]$/i.test(p.sourceName)},
  {id:'pharynx',title:'Pharynx',url:'https://www.wormatlas.org/hermaphrodite/pharynx/mainframe.htm',revision:'Chapter update announced 15 November 2024',text:'The pharynx is a muscular feeding pump with its own muscles, neurons, gland cells and structural cells.',quote:'The pharynx is an epithelial organ that has its own muscles, nervous system, gland cells and structural cells.',matches:(p:Part)=>/^Pharyngeal (muscles|epithelium|marginal)/.test(p.group)},
  {id:'egg',title:'Egg-laying apparatus',url:'https://www.wormatlas.org/hermaphrodite/egglaying%20apparatus/mainframe.htm',revision:'Page consulted 5 September 2026; revision date not established',text:'The egg-laying apparatus includes the uterus, vulva, their muscles and a local network of egg-laying neurons.',quote:'The egg-laying apparatus consists of the uterus, the uterine muscles, the vulva, the vulval muscles',matches:(p:Part)=>/vulv|uter/i.test(p.group)},
  {id:'gonad',title:'Somatic gonad',url:'https://www.wormatlas.org/hermaphrodite/somatic%20gonad/mainframe.htm',revision:'Page consulted 5 September 2026; revision date not established',text:'The somatic gonad is the non-germ-line component of the gonad. Its tissues include distal tip cells, sheath, spermatheca, spermatheca–uterine valve and uterus.',quote:'The somatic gonad refers to the non-germ-line component of each arm',matches:(p:Part)=>/gonadal sheath|spermathec|distal tip/i.test(p.group)}
];
export function ReferenceNotes({part}:{part:Part}){
  const notes=references.filter(r=>r.matches(part));
  return <>{notes.map(r=><div className="context-note" key={r.id}><h3>{r.title} · reference context</h3><p>{r.text}</p><a className="reference-link" href={r.url} target="_blank" rel="noreferrer">WormAtlas source ↗</a><small>{r.revision}. Context applies to the tissue or neuron class; it does not validate this mesh.</small></div>)}</>;
}
export function UpdatedSources(){return <div className="updated-sources"><h3>Source review · 5 September 2026</h3><p>The whole-body geometry remains dated 2012. The Neural EM view adds locally archived NeuroSC meshes from the 2021 study.</p><a className="reference-link" href="https://elifesciences.org/articles/103977" target="_blank" rel="noreferrer">NeuroSC · platform paper, 2025 ↗</a><a className="reference-link" href="https://www.nature.com/articles/s41586-021-03778-8" target="_blank" rel="noreferrer">Witvliet et al. · source study, 2021 ↗</a><h3>Reference annotations</h3>{references.map(r=><a className="reference-link" key={r.id} href={r.url} target="_blank" rel="noreferrer">{r.title} ↗</a>)}<p>WormFindr was announced on 4 March 2026. It is a candidate source; its geometry has not been imported or verified here.</p><a className="reference-link" href="https://www.wormatlas.org/framepage.htm" target="_blank" rel="noreferrer">WormAtlas updates / WormFindr ↗</a><a className="reference-link" href="./neurosc/catalog.json" target="_blank" rel="noreferrer">Neural dataset inventory and checksums ↗</a></div>;}
